import type { Insight } from "@/types";

// NOTE: Fictional sample data. In production these would be generated by
// permission-based AI analysis and always framed as suggestions, never as
// legal, financial, or insurance advice. See README "Security model".

export const insights: Insight[] = [
  {
    id: "in-internet",
    title: "Your internet contract renews soon",
    message:
      "This is often a good moment to ask for a loyalty rate or compare plans before it auto-renews.",
    insightType: "negotiation",
    priority: "medium",
    status: "active",
    relatedEntityType: "contract",
    relatedEntityId: "contract-internet",
  },
  {
    id: "in-insurance",
    title: "Renters insurance is expiring",
    message: "Compare coverage and price from a couple of providers before renewing.",
    insightType: "renewal",
    priority: "medium",
    status: "active",
    relatedEntityType: "contract",
  },
  {
    id: "in-smoke",
    title: "Smoke detector test is overdue",
    message: "A two-minute check. Worth doing before you forget it again.",
    insightType: "safety",
    priority: "high",
    status: "active",
    relatedEntityType: "maintenance",
  },
];
